rosbridge_websocket:
  ros__parameters:
    # Workaround for ROS2 Jazzy strict parameter typing:
    # this must be a float (DOUBLE), not an int.
    delay_between_messages: 0.0

    # Optional common settings (uncomment if you want to override defaults)
    # port: 9090
    # address: 0.0.0.0
